In [11]:
import pandas as pd

In [12]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [13]:
df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

### 1 concat()
#### 1.1 Concatenate vertically

In [14]:
df1 = pd.DataFrame({
    'id': ['A','B','C','D'],
    'age': [30, 23, 25, 22]
})
df2 = pd.DataFrame({
    'id': ['E','F','G','H'],
    'age': [40, 21, 19, 24]
})

In [15]:
pd.concat([df1, df2], ignore_index=True) 

# axis = 0 by default
# "ignore_index" ignores the index of the next dataframe

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

### 1.1.1 Exercise

In [20]:
# extract a 50% sample of the original dataframe (df_movies)

df_sample = df_movies.sample(frac=0.5)

In [24]:
# shape of dataframes that we'll concatenate
print(df_sample.shape)
print(df_movies.shape)

(42928, 5)
(85855, 5)

In [30]:
# concatenate df_movies and df_sample (vertically along the rows)
df_concat_vertically = pd.concat([df_movies, df_sample], ignore_index=True)
df_concat_vertically

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
128778,tt0109569,Visioni di un omicidio,1994,"Mystery, Thriller",USA
128779,tt0039829,Singapore,1947,"Action, Adventure, Crime",USA
128780,tt0052927,12 uomini da uccidere,1959,"Crime, Drama",USA
128781,tt3362908,Kruel,2015,"Horror, Thriller",USA
128782,tt0055526,Tintin et le mystère de la Toison d'Or,1961,"Adventure, Drama","France, Belgium"

In [31]:
# shape

print(df_concat_vertically.shape)

(128783, 5)

### Concatenate horizontally

In [34]:
df1 = pd.DataFrame({
    'id': ['A','B','C','D'],
    'age': [30, 23, 25, 22]
})
df2 = pd.DataFrame({
    'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']
})

In [ ]:
pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25    Accountant
3  D   22     Developer

### 1.2.1 Exercise

In [43]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
print(df_ratings.shape)

(85855, 5)
(85855, 3)

In [44]:
# concatenate df_movies and df_ratings on 'imdb_title_id' (horizontally along the columns)

df_concat_horizontally = pd.concat([df_movies, df_ratings], axis=1)
df_concat_horizontally.set_index('imdb_title_id', inplace=True)
df_concat_horizontally

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
"(tt0000009, tt0000009)",Miss Jerry,1894,Romance,USA,154,5.9
"(tt0000574, tt0000574)",The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
"(tt0001892, tt0001892)",Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
"(tt0002101, tt0002101)",Cleopatra,1912,"Drama, History",USA,446,5.3
"(tt0002130, tt0002130)",L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
"(tt9908390, tt9908390)",Le lion,2020,Comedy,"France, Belgium",398,5.5
"(tt9911196, tt9911196)",De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
"(tt9911774, tt9911774)",Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
"(tt9914286, tt9914286)",Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
"(tt9914942, tt9914942)",La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [45]:
# shape
print(df_concat_horizontally.shape)

(85855, 6)