In [33]:
import pandas as pd

In [34]:
# read csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)

# select necessary columns
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club', 'overall']]

# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### 1. sample()

In [35]:
# extract 10 random elements from the 'nationality' column

df['nationality'].sample(10, random_state=1)

short_name
D. Cvetinović            Serbia
M. Silva                Uruguay
S. Mandash         Saudi Arabia
I. Gruev               Bulgaria
Kangin Lee       Korea Republic
Marc Cardona              Spain
R. Nteka                 France
J. Mikel                Nigeria
He Chao                China PR
P. Ruffaut               France
Name: nationality, dtype: object

In [47]:
# extract a random 20% sample of the dataframe

df.sample(frac=0.2, random_state=12)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen,69
M. Nadé,Mickaël Nadé,20,1999-03-04,188,80,France,AS Saint-Étienne,58
V. García,Víctor Hugo García Hernández,25,1994-06-11,178,71,Venezuela,Vitória Guimarães,72
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848,54
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice,77
...,...,...,...,...,...,...,...,...
H. Kadish,Hassan Kadish,26,1992-09-26,179,73,Saudi Arabia,Al Hilal,65
A. Chapman,Aaron Chapman,29,1990-05-29,203,92,England,Peterborough United,63
I. Ezekiel,Imoh Ezekiel,25,1993-10-24,178,70,Nigeria,KV Kortrijk,68
H. Sakai,酒井 宏樹,29,1990-04-12,183,70,Japan,Olympique de Marseille,78
C. Keșerü,Claudiu Andrei Keșerü,32,1986-12-02,178,71,Romania,Romania,73

In [49]:
# upsample: increase the sampling rate -> frac>1 (Note: replace parameter has to be True for frac parameter > 1)

df.sample(frac=2, replace=True, random_state=99)

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle,62
A. Mosquera,Andrés Mosquera,29,1990-02-20,182,80,Colombia,Club León,73
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US Orléans Loiret Football,65
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Étienne,75
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC,57
...,...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC,50
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC,53
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna Düsseldorf,70
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City,55
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors,62